// <auto-generated />
using System;
using Carteira.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carteira.Web.Migrations
{
    [DbContext(typeof(CarteiraDbContext))]
    [Migration("20261009122609_AddValorCdiToSnapshots")]
    partial class AddValorCdiToSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carteira.Core.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classe");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.IndiceDiario", b =>
                {
                    b.Property<string>("Indice")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("indice");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("valor");

                    b.HasKey("Indice", "Data");

                    b.ToTable("indices_diarios", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.Operacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ChaveImportacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("import_key");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moeda");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("preco_unitario");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Taxas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("taxas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("titular_id");

                    b.HasKey("Id");

                    b.HasIndex("ChaveImportacao")
                        .IsUnique();

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.PrecoDiario", b =>
                {
                    b.Property<Guid>("AtivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("preco_unitario");

                    b.HasKey("AtivoId", "Data");

                    b.ToTable("daily_prices", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.Titular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("titulares", (string)null);
                });

            modelBuilder.Entity("Carteira.Web.SnapshotDiario", b =>
                {
                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("titular_id");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("custo");

                    b.Property<decimal>("CustoComPreco")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("custo_com_preco");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("rentabilidade");

                    b.Property<decimal>("ResultadoRealizado")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("resultado_realizado");

                    b.Property<bool>("TemPosicaoSemPreco")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_posicao_sem_preco");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorCdi")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("valor_cdi");

                    b.HasKey("Data", "TitularId");

                    b.HasIndex("TitularId", "Data");

                    b.ToTable("daily_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
