// <auto-generated />
using System;
using Carteira.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carteira.Web.Migrations
{
    [DbContext(typeof(CarteiraDbContext))]
    partial class CarteiraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carteira.Core.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classe");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.DailyPrice", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("preco_unitario");

                    b.HasKey("AssetId", "Data");

                    b.ToTable("daily_prices", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.Titular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("titulares", (string)null);
                });

            modelBuilder.Entity("Carteira.Core.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ChaveImportacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("import_key");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moeda");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("preco_unitario");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Taxas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("taxas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("titular_id");

                    b.HasKey("Id");

                    b.HasIndex("ChaveImportacao")
                        .IsUnique();

                    b.ToTable("trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
